on:
  workflow_call:
    inputs:
      minimal:
        description: minimal dataset
        type: boolean
        required: false
        default: true
    outputs:
      version:
        value: ${{ jobs.download.outputs.version }}
      cache_path:
        value: ${{ jobs.download.outputs.cache_path }}
      cache_key:
        value: ${{ jobs.download.outputs.cache_key }}
  workflow_dispatch:
    inputs:
      minimal:
        description: minimal dataset
        type: boolean
        required: false
        default: true
  schedule:
    - cron: "0 0 * * 0"

env:
  DATA_URL: https://stsci.box.com/shared/static/qxpiaxsjwo15ml6m4pkhtk36c9jgj70k.gz
  MINIMAL_DATA_URL: https://stsci.box.com/shared/static/gkbnn3jwcootr9riwv0rv1t8rpvxl3vr.gz

jobs:
  download:
    name: download and cache WebbPSF data
    runs-on: ubuntu-latest
    steps:
      - run: wget ${{ github.event_name == 'schedule' && env.MINIMAL_DATA_URL || inputs.minimal && env.MINIMAL_DATA_URL || env.DATA_URL }} -O ${{ runner.temp }}/webbpsf-data.tar.gz
      - run: tar -xzvf ${{ runner.temp }}/webbpsf-data.tar.gz -C ${{ runner.temp }}
      - id: cache_path
        run: echo cache_path=${{ runner.temp }}/webbpsf-data >> $GITHUB_OUTPUT
      - id: version
        run: echo "version=$(cat ${{ steps.cache_path.outputs.cache_path }}/version.txt)" >> $GITHUB_OUTPUT
      - id: cache_key
        run: echo "cache_key=webbpsf-data-${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT
      - uses: actions/cache/save@v4
        with:
          path: ${{ runner.temp }}/webbpsf-data
          key: ${{ steps.cache_key.outputs.cache_key }}
    outputs:
      version: ${{ steps.version.outputs.version }}
      cache_path: ${{ steps.cache_path.outputs.cache_path }}
      cache_key: ${{ steps.cache_key.outputs.cache_key }}
     
