on:
  workflow_call:
    inputs:
      minimal:
        description: minimal dataset
        type: boolean
        required: false
        default: true
    outputs:
      version:
        value: ${{ jobs.retrieve_latest_cache_key.outputs.version }}
      cache_path:
        value: ${{ jobs.retrieve_latest_cache_key.outputs.cache_path }}
      cache_key:
        value: ${{ jobs.retrieve_latest_cache_key.outputs.cache_key }}

jobs:
  retrieve_latest_cache_key:
    name: retrieve latest WebbPSF data cache key
    runs-on: ubuntu-latest
    steps:
      - name: retrieve latest data cache key
        id: latest_cache_key
        run: |
          # use actions/gh-actions-cache to allow filtering by key
          gh extension install actions/gh-actions-cache
          CACHE_KEY=$(gh actions-cache list -R ${{ github.repository }} --key webbpsf-data-${{ inputs.minimal && 'mini' || 'full' }}- --sort created-at | cut -f 1 | head -n 1)
          if [ "$CACHE_KEY" == '' ]; then exit 1; fi
          echo cache_key=$CACHE_KEY >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - run: echo ${{ steps.latest_cache_key.outputs.cache_key }}
      - id: version
        run: echo "version=$(${{ steps.latest_cache_key.outputs.cache_key }} | awk -F '-' '{print $4}')" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.version.outputs.version }}
      cache_path: ${{ runner.temp }}/webbpsf-data
      cache_key: ${{ steps.latest_cache_key.outputs.cache_key }}
